from django.conf import settings
from django.conf.urls import include, url
from django.views.generic.base import RedirectView
from . import views
from . import auth

urlpatterns = [
    url(r'^auth/login/$', auth.ThrottledLoginView.as_view(), name='login'),
    url(r'^auth/', include('django.contrib.auth.urls')),
    url(r'^courts$', views.courts, name='courts'),
    url(r'^courts_export$', views.courts_export, name='courts_export'),
    url(r'^courts_by_aol/(?P<aol>[\w ]+)$', views.courts_by_aol, name='courts_by_aol'),
    url(r'^court/new$', views.new_court, name='new_court'),
    url(r'^court/delete/(?P<id>[0-9]+)$', views.delete_court, name='delete_court'),
    url(r'^court/(?P<id>[0-9]+)$', views.edit_court, name='court'),
    url(r'^court/(?P<id>[0-9]+)/types$', views.edit_types, name='types'),
    url(r'^court/(?P<id>[0-9]+)/location$', views.edit_location, name='location'),
    url(r'^court/(?P<id>[0-9]+)/location/geo$', views.locate_postcode, name='geolocation'),
    url(r'^court/(?P<id>[0-9]+)/address$', views.edit_address, name='address'),
    url(r'^court/(?P<id>[0-9]+)/address/(?P<address_id>[0-9]+)$', views.edit_address, name='address'),
    url(r'^court/(?P<id>[0-9]+)/delete_address/(?P<address_id>[0-9]+)$', views.delete_address, name='delete_address'),
    url(r'^court/(?P<id>[0-9]+)/contact$', views.ContactFormView.as_view(), name='contact'),
    url(r'^court/(?P<id>[0-9]+)/add_contact$', views.AddContactView.as_view(), name='add_contact'),
    url(r'^court/(?P<id>[0-9]+)/reorder_contacts', views.ContactReorderView.as_view(), name='reorder_contacts'),
    url(r'^court/(?P<id>[0-9]+)/email$', views.EmailFormView.as_view(), name='email'),
    url(r'^court/(?P<id>[0-9]+)/add_email$', views.AddEmailView.as_view(), name='add_email'),
    url(r'^court/(?P<id>[0-9]+)/reorder_emails$', views.EmailReorderView.as_view(), name='reorder_emails'),
    url(r'^court/(?P<id>[0-9]+)/opening_times$', views.OpeningFormView.as_view(), name='opening'),
    url(r'^court/(?P<id>[0-9]+)/add_opening_times$', views.AddOpeningView.as_view(), name='add_opening'),
    url(r'^court/(?P<id>[0-9]+)/reorder_opening_times$', views.OpeningReorderView.as_view(), name='reorder_openings'),
    url(r'^court/(?P<id>[0-9]+)/facility$', views.FacilityFormView.as_view(), name='facility'),
    url(r'^court/(?P<id>[0-9]+)/add_facility$', views.AddFacilityView.as_view(), name='add_facility'),
    url(r'^court/(?P<id>[0-9]+)/reorder_facilities$', views.FacilityReorderView.as_view(), name='reorder_facilities'),
    url(r'^court/(?P<id>[0-9]+)/areas_of_law$', views.areas_of_law, name='aols'),
    url(r'^court/(?P<id>[0-9]+)/leaflets$', views.edit_leaflets, name='leaflets'),
    url(r'^court/(?P<id>[0-9]+)/postcodes$', views.edit_postcodes, name='postcodes'),
    url(r'^court/(?P<id>[0-9]+)/add_postcodes$', views.add_postcodes, name='add_postcodes'),
    url(r'^court/(?P<id>[0-9]+)/family(?:/(?P<area_id>[0-9]+))?$', views.edit_family_court, name='family'),
    url(r'^court/(?P<id>[0-9]+)/photo$', views.photo_upload, name='photo'),
    url(r'^court/(?P<id>[0-9]+)/photo_delete$', views.photo_delete, name='photo_delete'),
    url(r'^court/(?P<id>[0-9]+)/gbs$', views.edit_gbs, name='gbs'),
    url(r'^users$', views.users, name='users'),
    url(r'^users/new$', views.add_user, name='add_user'),
    url(r'^users/edit/(?P<username>\S+)$', views.edit_user, name='edit_user'),
    url(r'^users/delete/(?P<username>\S+)$', views.delete_user, name='delete_user'),
    url(r'^users/password/(?P<username>\S+)$', views.change_user_password, name='user_password'),
    url(r'^account$', views.account, name='account'),
    url(r'^emergency$', views.emergency_message, name='emergency'),
    url(r'^facility_types$', views.FacilityList.as_view(), name='facility_types'),
    url(r'^contact_types$', views.ContactList.as_view(), name='contact_types'),
    url(r'^opening_types$', views.OpeningList.as_view(), name='opening_types'),
    url(r'^aols$', views.AreaOfLawList.as_view(), name='aols'),
    url(r'^edit_facility_type/$', views.EditFacilityType.as_view(), name='edit_facility_type'),
    url(r'^edit_facility_type/(?P<id>[0-9]+)$', views.EditFacilityType.as_view(), name='edit_facility_type'),
    url(r'^edit_facility_type/(?P<id>[0-9]+)/photo$', views.facility_icon_upload, name='facility_icon_upload'),
    url(r'^delete_facility_type/$', views.DeleteFacilityType.as_view(), name='delete_facility_type'),
    url(r'^edit_contact_type/$', views.EditContactType.as_view(), name='edit_contact_type'),
    url(r'^edit_contact_type/(?P<id>[0-9]+)$', views.EditContactType.as_view(), name='edit_contact_type'),
    url(r'^delete_contact_type/$', views.DeleteContactType.as_view(), name='delete_contact_type'),
    url(r'^edit_opening_type/$', views.EditOpeningType.as_view(), name='edit_opening_type'),
    url(r'^edit_opening_type/(?P<id>[0-9]+)$', views.EditOpeningType.as_view(), name='edit_opening_type'),
    url(r'^delete_opening_type/$', views.DeleteOpeningType.as_view(), name='delete_opening_type'),
    url(r'^edit_aol/$', views.EditAOL.as_view(), name='edit_aol'),
    url(r'^edit_aol/(?P<id>[0-9]+)$', views.EditAOL.as_view(), name='edit_aol'),
    url(r'^reorder_facility_types/$', views.ReorderingFacilityList.as_view(), name='reorder_facility_types'),
    url(r'^$', RedirectView.as_view(pattern_name=settings.LOGIN_REDIRECT_URL))
]

