language: python
dist: trusty
addons:
  chrome: stable
node_js:
  - "0.10"
python:
  - "3.6"
notifications:
  email: false
services:
  - postrgresql
before_install:
  - sudo apt-get -qq update
  - sudo ./apt/base.sh
  - sudo ./apt/testing.sh
  - wget -N https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - sudo mv ~/chromedriver /usr/local/bin/chromedriver
install:
  - "pip install setuptools==46"
  - "pip install -r requirements.txt"
  - "pip install -r requirements/testing.txt"
  - "npm config set registry http://registry.npmjs.org/"
  - "npm install"
  - "sudo gem install sass -v 3.4.21"
env:
  - POSTGRES_USER=postgres DJANGO_SETTINGS_MODULE=courtfinder.settings.test
before_script:
  - "psql -c 'CREATE DATABASE courtfinder_search;' -U postgres"
  - "$(npm bin)/gulp"
  - "cd courtfinder"
  - "python manage.py migrate --noinput"
  - "python manage.py compilemessages"
script:
  - coverage run --source='.' manage.py test
  - coverage report
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then codeclimate-test-reporter; fi
  - python manage.py loaddata  ../features/fixtures.yaml 2>/dev/null
  - python manage.py runserver &
  - sleep 2
  - cd ..
  - behave --format progress3 -Dheadless --tags=-wip
