language: python
dist: trusty
node_js:
  - "0.10"
python:
  - "2.7"
notifications:
  email: false
services:
  - postrgresql
before_install:
  - sudo ./apt/base.sh
  - sudo ./apt/testing.sh
install:
  - "pip install setuptools==32"
  - "pip install -r requirements.txt"
  - "pip install -r requirements/testing.txt"
  - "npm config set registry http://registry.npmjs.org/"
  - "npm install"
  - "sudo gem install sass -v 3.4.21"
env:
  - POSTGRES_USER=postgres DJANGO_SETTINGS_MODULE=courtfinder.settings.test
before_script:
  - "psql -c 'CREATE DATABASE courtfinder_search;' -U postgres"
  - "$(npm bin)/gulp"
  - "cd courtfinder"
  - "python manage.py migrate --noinput"
  - "python manage.py populate-db --datadir=../data/test_data --ingest"
script:
  - "python manage.py test"
