FROM python:2.7-slim

RUN useradd -m -d /srv/search search
WORKDIR /srv/search

# Install system dependencies and generate assets
COPY apt/ ./apt
COPY package.json gulpfile.js ./
COPY docker/ ./docker
COPY courtfinder/assets-src/ ./courtfinder/assets-src
RUN apt-get update && ./apt/production.sh \
      && ./docker/setup_npm.sh && npm run gulp && rm -rf ./node_modules \
      && apt-get purge -y --auto-remove ruby npm nodejs \
      && rm -rf /var/lib/apt/lists/*

# Install python dependencies
COPY requirements/ ./requirements
RUN pip install --no-cache-dir -r ./requirements/local.txt

# Collect static assets
ENV DJANGO_SETTINGS_MODULE courtfinder.settings.production
COPY courtfinder/ ./courtfinder
RUN python courtfinder/manage.py collectstatic --noinput && \
    mkdir -p /srv/logs && chown -R search:search /srv/logs && \
    chown -R search: /srv/search

COPY . .

USER search

CMD ./run.sh

EXPOSE 8000
