# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_facility_image_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='addresses',
            field=models.ManyToManyField(through='search.CourtAddress', to='search.AddressType'),
        ),
        migrations.AlterField(
            model_name='court',
            name='areas_of_law',
            field=models.ManyToManyField(through='search.CourtAreaOfLaw', to='search.AreaOfLaw'),
        ),
        migrations.AlterField(
            model_name='court',
            name='attributes',
            field=models.ManyToManyField(through='search.CourtAttribute', to='search.CourtAttributeType'),
        ),
        migrations.AlterField(
            model_name='court',
            name='contacts',
            field=models.ManyToManyField(through='search.CourtContact', to='search.Contact'),
        ),
        migrations.AlterField(
            model_name='court',
            name='court_types',
            field=models.ManyToManyField(through='search.CourtCourtType', to='search.CourtType'),
        ),
        migrations.AlterField(
            model_name='court',
            name='emails',
            field=models.ManyToManyField(through='search.CourtEmail', to='search.Email'),
        ),
        migrations.AlterField(
            model_name='court',
            name='facilities',
            field=models.ManyToManyField(through='search.CourtFacility', to='search.Facility'),
        ),
        migrations.AlterField(
            model_name='court',
            name='opening_times',
            field=models.ManyToManyField(through='search.CourtOpeningTime', to='search.OpeningTime'),
        ),
        migrations.AlterField(
            model_name='datastatus',
            name='last_ingestion_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
