# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_courtopeningtime_sort'),
        ('search', '0016_upgrade_django_1_11'),
    ]

    operations = [
    ]
