# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_court_magistrate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtemail',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
