# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_auto_20180312_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='alert',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='defence_leaflet',
            field=models.CharField(blank=True, default=None, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='info_leaflet',
            field=models.CharField(blank=True, default=None, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='juror_leaflet',
            field=models.CharField(blank=True, default=None, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='prosecution_leaflet',
            field=models.CharField(blank=True, default=None, max_length=2500, null=True),
        ),
    ]
