# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_auto_20180410_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='explanation',
            field=models.CharField(max_length=85, null=True),
        ),
    ]
