# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-20 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0022_email_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtaddress',
            name='town_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
