# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-21 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0023_courtaddress_town_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtaddress',
            name='town',
        ),
        migrations.DeleteModel(
            name='Town',
        ),
    ]
