# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-25 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0024_auto_20180621_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingtime',
            name='hours',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='openingtime',
            name='type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
