# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-29 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_auto_20180625_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingtime',
            name='description',
        ),
    ]
