# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-09 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0026_remove_openingtime_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='welsh_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
