# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-09 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_court_welsh_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='alert_cy',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='directions_cy',
            field=models.CharField(blank=True, default=None, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='info_cy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
