# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-10 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0028_auto_20180709_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='explanation_cy',
            field=models.CharField(max_length=85, null=True),
        ),
    ]
