# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-10 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0029_contact_explanation_cy'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='explanation_cy',
            field=models.CharField(max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='description_cy',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
