# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-10 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0030_auto_20180710_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='defence_leaflet_cy',
            field=models.CharField(blank=True, default=None, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='info_leaflet_cy',
            field=models.CharField(blank=True, default=None, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='prosecution_leaflet_cy',
            field=models.CharField(blank=True, default=None, max_length=2500, null=True),
        ),
    ]
