# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-23 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0031_auto_20180710_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaoflaw',
            name='external_link_desc_cy',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
