# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-03 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0035_auto_20180830_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='name_cy',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
