# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-01 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_openingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitytype',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
