# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-23 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_facilitytype_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttype',
            name='name_cy',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facilitytype',
            name='image_description_cy',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facilitytype',
            name='name_cy',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='openingtype',
            name='name_cy',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
